<?php echo $this->doctype(); ?>

<html lang="en" >
    <head>
        <script>
        function subst() {
          var vars={};
          var x=window.location.search.substring(1).split('&');
          for (var i in x) {var z=x[i].split('=',2);vars[z[0]] = unescape(z[1]);}
          var x=['frompage','topage','page','webpage','section','subsection','subsubsection'];
          for (var i in x) {
            var y = document.getElementsByClassName(x[i]);
            if (typeof y !== "undefined") {
                for (var j=0; j<y.length; ++j) y[j].textContent = vars[x[i]];
            }
          }
        }
        </script>

        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Centurion Assesment Portal'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php
            /*
            echo $this->headLink(array('rel' => 'shortcut icon',
                                       'type' => 'image/vnd.microsoft.icon',
                                       'href' => $this->basePath() . '/img/favicon.ico'));
            */
            //echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css');

        ?>
        <link href="http://localhost/css/pdf-style.css" media="screen" rel="stylesheet" type="text/css"/>

        <!-- Scripts -->
        <?php echo $this->headScript()
            //->prependFile($this->basePath() . '/js/cap.min.js')
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript')
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript')
        ; ?>
    </head>
    <body onload="subst()">
        <div class="container-fluid">
            <?php echo $this->content ?>
        </div>
    </body>
</html>
