<!-- footer -->
<div id="footer" class="cap-footer">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">

		</div>
	</div>
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="footer-logo">
			<div class="footer-img pull-right">
	    	<img class="img-responsive" src="/img/Optimum-Training-Logo-left-light1.png"/>
	    </div>
			<div class="powered-by pull-right"><i><strong>POWERED BY</strong></i></div>
		</div>
	</div>
</div>
