<?php echo $this->doctype(); ?>

<html lang="en" ng-app="cap">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Centurion Assesment Portal'))->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0')->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); ?>

        <?php
            /*
            echo $this->headLink(array('rel' => 'shortcut icon',
                                       'type' => 'image/vnd.microsoft.icon',
                                       'href' => $this->basePath() . '/img/favicon.ico'));
            */
            echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css');
        ?>
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/cap.min.js')
            //->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript')
            //->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript')
        ; ?>
    </head>
    <body>
        <div id="overlay" cap-overlay>
            <div class="overlay-loading hide">
                <div>
                    <img src="/img/optimum-links.png"/>
                </div>
                <div ng-show="message">
                    <i class="fa fa-cog fa-spin fa-fw"></i>
                    <span>[[message]]</span>
                </div>
            </div>
        </div>
        <?php echo $this->partial('layout/nav') ?>
        <div id="content" class="container-fluid">
            <?php echo $this->content ?>
        </div>
        <?php echo $this->partial('layout/footer') ?>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
