<?php $this->headScript()->prependFile($this->basePath() . '/js/'. strtolower($this->identity()->getRole()->getName()) .'.min.js') ?>

<div class="row" ng-controller="QuestionnaireCtrl" ng-init="init()">
    <div class="col-xs-10 col-xs-offset-1 questionnaire summary">
        <div class="row">
            <div class="col-xs-12">
                <h1>Skills Assesment Questionnaire</h1>
            </div>
        </div>

        <div class="row">
        	<div class="col-xs-offset-1 col-xs-10">
        		<div class="row">
        			<div class="col-xs-8">
        				<h2 class="alt"><?php echo $questionnaire->getName() ?></h2>
        			</div>
        			<div class="col-xs-4 text-right">
        				<span class="percent-complete"><?php echo $sectionData['percentComplete'] ?></span>
        			</div>
        		</div>
        		<div class="row">
        			<div class="col-xs-12">
        				<span class="description"><?php echo $questionnaire->getDescription() ?></span>
        			</div>
        		</div>
        		<div class="row">
        			<div class="col-xs-12 summary-box">
        				<?php foreach ($sections as $section) { ?>
	        				<div class="row">
	        					<div class="col-xs-5">
	        						<h3 class="section-name"><?php echo $section->getSectionNumber() .". " . $section->getName() ?></h3>
	        					</div>
	        					<div class="col-xs-4">
	        						<span class="summary-text"><?php echo $sectionData[$section->getSectionNumber()]['completedQuestionCount'] ." of ".$sectionData[$section->getSectionNumber()]['questionCount'] . ' questions completed.' ?>
	        					</div>
	        					<div class="col-xs-3">
	        						<span class="completion-status"><?php echo $sectionData[$section->getSectionNumber()]['completionStatus'] ?></span>
	        					</div>
	        				</div>
	        			<?php } ?>
        				<div class="row">
        					<div class="col-xs-12">
        						<?php
        							if (!isset($nextSection)) {
        								$nextSection = 1;
        							}
        							if (!isset($nextPage)) {
        								$nextPage = 1;
        							}

        							$key = 'questionnaire/view';
        							$urlArgs = array('questionnaireId' => $questionnaire->getId(),
        															 'sectionNumber'   => $nextSection,
																			 'action'          => 'page',
																			 'id'              => $nextPage);

        							if (isset($customer)) {
        								$key = 'questionnaire/complete';
												$urlArgs['customerId'] = $customer->getId();
        							}

        							$url = $this->url($key, $urlArgs);

        						?>
                    <a href="<?php echo $url; ?>" class="btn btn-primary">Continue</a>

        					</div>
        				</div>
        			</div>
        		</div>
        	</div>
        </div>
    </div>
</div>
