<div id="confirm-continue-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">
        	<span aria-hidden="true">
        		<i class="fa fa-times"></i>
        	</span>
        	<span class="sr-only">Close</span>
        </button>
        <h4 class="modal-title" id="myModalLabel">Are you sure?</h4>
      </div>
      <div class="modal-body">
        <div class="row">
          <div class="col-xs-12"><div class="alert alert-warning">You have completed this section.  Once you continue to the next section, you will not be able to change any answers for this section.  Are you sure you're ready to continue?</div></div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="row">
          <div class="col-xs-6">
            <button type="button" class="btn btn-default form-control" data-dismiss="modal">No, Cancel</button>
          </div>
          <div class="col-xs-6">
            <a href="[[nextUrl]]" class="btn btn-primary form-control">Yes I'm sure, Continue</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
