<div class="row">
	<div class="col-xs-4 form-group" ng-repeat="answer in answers track by $index">
		<label ng-disabled="disabled">
			<i ng-hide="answer.checked" class="fa fa-square-o fa-fw"></i>
			<i ng-show="answer.checked" class="fa fa-check-square-o green fa-fw"></i>
			<input ng-change="save()" type="checkbox" ng-disabled="disabled" ng-model="answer.checked" class="hide">
			<span>[[answer.answerText]]</span>
		</label>
	</div>
</div>
