<div class="row">
	<div class="col-xs-12">
		<div class="row" style="margin:0">
			<div class="col-xs-12">
				<div class="row enum-heading">
					<div class="col-xs-offset-4 col-xs-8">
						<div class="row enum-grid">
							<div class="[[enumColsClass]] enum-answer-col-heading text-center" ng-repeat="answerEnum in answers[0].answerEnums">[[answerEnum.name]]</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="row enum-container">
	<div ng-class="{0:'first'}[$index]" class="col-xs-12 enum-row" ng-repeat="answer in answers">
		<div class="row enum-answer-row">
			<div class="col-xs-4 enum-answer-heading">[[answer.answerNumber]]. [[answer.answerText]]</div>
			<div class="col-xs-8 enum-answer-enum-container">
				<div class="row enum-grid">
					<div class="[[enumColsClass]] enum-answer-col text-center" ng-repeat="answerEnum in answer.answerEnums">
						<label ng-disabled="disabled">
							<i ng-hide="answer.selectedEnumId==answerEnum.id" class="fa fa-circle-o fa-fw"></i>
							<i ng-show="answer.selectedEnumId==answerEnum.id" class="fa fa-check-circle-o green fa-fw"></i>
							<input ng-change="save()" name="[[questionId]]-[[answer.id]]" type="radio" ng-disabled="disabled" ng-model="answer.selectedEnumId" value="[[answerEnum.id]]" class="hide">
						</label>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
