<div class="row">
	<div class="col-xs-12 form-group" ng-repeat="answer in answers">
		<div class="row">
			<div class="col-xs-3">[[answer.answerNumber]]. [[answer.answerText]]</div>
			<div class="col-xs-9">
				<div class="row">
					<div class="[[enumColsClass]]" ng-repeat="answerEnum in answer.answerEnums">
						<label ng-disabled="disabled">
							<i ng-hide="answer.selectedEnumId==answerEnum.id" class="fa fa-circle-o fa-fw"></i>
							<i ng-show="answer.selectedEnumId==answerEnum.id" class="fa fa-check-circle-o green fa-fw"></i>
							<input ng-change="save()" name="[[questionId]]-[[answer.id]]" type="radio" ng-disabled="disabled" ng-model="answer.selectedEnumId" value="[[answerEnum.id]]" class="hide">
							<span>[[answerEnum.name]]</span>
						</label>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
