<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CapAuth\Module'                       => __DIR__ . '/Module.php',
    'CapAuth\Controller\AuthController'    => __DIR__ . '/src/CapAuth/Controller/AuthController.php',
    'CapAuth\Model\MyAuthStorage'          => __DIR__ . '/src/CapAuth/Model/MyAuthStorage.php',
);
