<?php //TODO: what to do if there are no mentees for a mentor ?>

<div class="row" ng-controller="DashboardCtrl", ng-init="init()" id="dashboard">
    <div class="col-xs-10 col-xs-offset-1">
    	<div class="row">
    		<div class="col-xs-12">
    			<p>Welcome!  Orbital’s future holds many opportunities for top employees who are motivated to acquire fresh skills and who will actively work to broaden themselves.   You, as one of the mentors selected to participate in Orbital’s mentoring program will be an integral part of our success.  In this regard, mentoring will serve as an equal partner to formal training and other developmental efforts in the reinvention and revitalization of Orbital’s workforce.</p>
					<p>This Centurion Assessment Portal (CAP) will allow you to view and create notes on your mentee’s assessments for later discussion.   Your mentee will also be able to create and share notes with you.</p>
    		</div>
    	</div>
        <?php
            echo $this->partial('/cap/partials/forms-list');
            echo $this->partial('/cap/partials/mentees-list');
        ?>
    </div>
</div>
