<?php $this->headScript()->prependFile($this->basePath() . '/js/'. strtolower($this->identity()->getRole()->getName()) .'.min.js') ?>
<div class="row" ng-controller="MentorCtrl" ng-init="init('<?php echo $mentor->getId()?>')">
    <div class="col-xs-10 col-xs-offset-1">
		    <?php
		    	if ($this->identity()->getRole()->getName() === 'Admin') {
		    		echo $this->partial('/cap/partials/assign-mentee-modal');
		    	}
	      	echo $this->partial("cap/partials/view-note-modal");
	      	echo $this->partial("cap/partials/edit-note-modal");
	      	echo $this->partial("cap/partials/create-note-modal");
        	echo $this->partial("cap/partials/customer-info", array('type' => 'mentor', 'title' => 'Mentor Information', 'customer' => $mentor));
	      	echo $this->partial("cap/partials/mentees-list");

	      	if ($this->identity()->getRole()->getName() !== 'Admin') {
	      		echo $this->partial("cap/partials/notes-list",array('title' => 'My Notes','notes' => 'myNotes'));
	      		echo $this->partial("cap/partials/notes-list",array('title' => 'Notes Shared With Me','notes' => 'sharedNotes'));
	      	}

	      ?>
	  </div>
</div>
