<?php $this->headScript()->prependFile($this->basePath() . '/js/login.min.js') ?>

<div class="row">
    <div class="login-box col-xs-12 col-md-6 col-md-offset-3" ng-controller="ResetPasswordCtrl" ng-init="init()">
        <div class="row">
            <div class="login-header col-xs-12">
                <h2> Centurion Assessment Portal Password Reset</h2>
            </div>
        </div>
        <div class="row">
            <form novalidate name="resetPasswordForm" class="col-xs-12" ng-submit="submitResetPassword()">
                <div class="row" ng-show="success">
                    <div class="col-xs-12 login-error">
                        <div ng-show="resetPasswordForm.$dirty && msg" class="alert alert-success">
                            <span>[[msg]]</span>
                        </div>
                    </div>
                </div>
                <div class="row" ng-hide="success">
                    <div class="col-xs-12 login-error">
                        <div ng-show="resetPasswordForm.$dirty && msg" class="alert alert-warning">[[msg]]</div>
                    </div>
                </div>
                <div class="row">
                    <div class="text-input form-group col-xs-12">
                        <div class="row">
                            <label class="col-xs-5">Email Address:</label>
                            <div class="col-xs-7">
                                <input class="form-control" type="text" name="email" ng-model="email" required/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-xs-5 forgot-password">
                        <a href="/">Back to login...</a>
                    </div>
                    <div class="col-xs-7">
                        <button type="submit" ng-disabled="inProgress" class="btn btn-primary form-control" name="submit">
                            <i class="fa fa-lock"></i>
                            <span>Request Password Reset Email</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

